### ISSUE TITLE
fillFormWithDataAndCallHooks(): Argument #1 ($data) must be of type array, App\Models\Journey given

### ISSUE THREAD

**Issue by tsalim13** [lara-zeus/translatable#11]
i got this error with EditRecord and ViewRecord

![image](https://github.com/lara-zeus/translatable/assets/25728844/d2adbf9d-209b-46ca-8c8b-c8d6011bf401)

**Comment by dinmezpinar** [comment]
I have the same error too. Any solutions?

**Comment by atmonshi** [comment]
- are you using this fork or the original filament package?
- can you provide the code and steps to reproduce?
- any more details than the error message so I can help you?

**Comment by dinmezpinar** [comment]
My Laravel version was v10.10 and my Filament version was 3.0. I resolved my issue by updating Filament to version 3.2 and Laravel to version 11.0. Thank you for your support.
