### ISSUE TITLE
Validation issue on locale switch

### ISSUE THREAD

**Issue by ivl04** [lara-zeus/translatable#12]
I have used this repository to store multi-language data in JSON datatype. After switching from the base plugin to this repository, I encountered an issue with the locale switch.

Steps to Reproduce:
Add a translation field with required validation.
Enter data in the default language (in my case, English).
Save the data to ensure it is stored.
Switch to another language using the locale switcher option.
Switch back to English.
At this point, the data from the English field is lost, resulting in a validation error.

bubble: (https://app.usebubbles.com/iXL1hc6n5nFRZs3T9JPDLZ/spatie-translatable-plugin-issue-on-locale-switcher)

if bubble expire you can refer ss
screenshot :

https://img.enacton.com/ShareX/2024/06/chrome_yfcctbhrrP.png
https://img.enacton.com/ShareX/2024/06/chrome_tSzQ1NmeiL.png
https://img.enacton.com/ShareX/2024/06/chrome_GyxtZvhLyv.png

**Comment by atmonshi** [comment]
the validation is for the other language not the english, if you fill in and switch the lang and back to english, the data still there.

the issue is the lang switcher should be prevented from switching if there is a validation error

**Comment by atmonshi** [comment]
did a fix #13 , can you test if it fix the issue?
